apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chatbot
  name: chatbot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - image: gcr.io/${PROJECT_ID}/nthu-line-flask:latest
        imagePullPolicy: Always
        name: nthu-line-flask
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 5000
        env:
            - name: LINE_OFFICIAL_TOKEN 
              valueFrom: 
                secretKeyRef:
                  name: line-official-token # kubernetes secret
                  key: password
            - name: LINE_WEBHOOK_STRING 
              valueFrom: 
                secretKeyRef:
                  name: line-webhook-string # kubernetes secret
                  key: password
