apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chatbot
  name: chatbot
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - image: gcr.io/nthu-chatbot/github.com/nthuagent/nthu-campus-agent-line-flask
        imagePullPolicy: Always
        name: nthu-line-flask
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            cpu: "250m"
            ephemeral-storage: 1Gi
            memory: "512Mi"
          limits:
            cpu: "250m"
            ephemeral-storage: 1Gi
            memory: "512Mi"
        env:
            - name: LINE_OFFICIAL_TOKEN 
              valueFrom: 
                secretKeyRef:
                  name: line-official-token # kubernetes secret
                  key: password
            - name: LINE_WEBHOOK_STRING 
              valueFrom: 
                secretKeyRef:
                  name: line-webhook-string # kubernetes secret
                  key: password
            - name: GINIP
              valueFrom:
                configMapKeyRef:
                  name: gin-config
                  key: ginip
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chatbot
  name: chatbot-service
  namespace: default
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - nodePort: 32422
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: chatbot
  type: NodePort
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: chatbot
  namespace: default
spec:
  maxReplicas: 2
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chatbot
